"""
watch_outputs.py
================
Daemon that continuously watches the outputs/ directory for new response.json files
generated by Hemang's architecture. When a new file is detected, it automatically
triggers the Execution Engine!

Usage:
    python3 watch_outputs.py
"""

import time
from pathlib import Path
import json
from execution.queue import process_arbitration

def get_latest_response():
    outputs_dir = Path("outputs")
    if not outputs_dir.exists():
        return None
    
    contexts = list(outputs_dir.rglob("response.json"))
    if not contexts:
        return None
        
    return max(contexts, key=lambda p: p.stat().st_mtime)

def watch():
    print("[Watcher] Watching outputs/ directory for new voice commands...")
    last_processed_file = None
    last_processed_mtime = 0
    
    while True:
        latest_file = get_latest_response()
        
        if latest_file:
            mtime = latest_file.stat().st_mtime
            # Process if it's a completely new file, or if the file was updated recently
            if latest_file != last_processed_file or mtime > last_processed_mtime:
                # Wait a tiny bit just to ensure Hemang's code finished writing to it
                time.sleep(0.5)
                
                print(f"\n[Watcher] New command detected: {latest_file}")
                try:
                    with open(latest_file, "r") as f:
                        payload = json.load(f)
                    process_arbitration(payload)
                except Exception as e:
                    print(f"Error processing {latest_file}: {e}")
                    
                last_processed_file = latest_file
                last_processed_mtime = mtime
                
        time.sleep(1)

if __name__ == "__main__":
    try:
        watch()
    except KeyboardInterrupt:
        print("\nStopping watcher.")
